name: Java
on:
  push:
    branches: [ master ]
    paths-ignore:
      - ".github/dependabot.yml"
      - '.*ignore'
      - 'LICENSE'
      - '*.md'
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ${{ matrix.platform.os }}
    timeout-minutes: 10
    strategy:
      matrix:
        platform:
          - name: linux-java11
            os: ubuntu-latest
            java: 11
            maven_opts: --add-opens=java.base/java.lang=ALL-UNNAMED
          - name: linux-java17
            os: ubuntu-latest
            java: 17
            maven_opts: --add-opens=java.base/java.lang=ALL-UNNAMED
          - name: linux-java21
            os: ubuntu-latest
            java: 21
            maven_opts: --add-opens=java.base/java.lang=ALL-UNNAMED
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: set up jdk
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.platform.java }}
          distribution: temurin
      - name: verify
        env:
          MAVEN_OPTS: ${{ matrix.platform.maven_opts }}
        run: mvn --batch-mode --update-snapshots clean verify